branches:
  - master
  - name: beta
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: "packages/graphql/CHANGELOG.md"
  - - "@semantic-release/changelog"
    - changelogFile: "packages/graphql_flutter/CHANGELOG.md"
  - - "@semantic-release/git"
    - assets:
        - "packages/graphql/CHANGELOG.md"
        - "packages/graphql_flutter/CHANGELOG.md"
  - "@semantic-release/github"
